volumes:
  kafka-data:
    driver: local

  product_db:
    driver: local

networks:
  reverse-proxy:

services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: event_bus
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      reverse-proxy:
        aliases:
          - event_bus
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://event_bus:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@event_bus:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKAJS_NO_PARTITIONER_WARNING: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: event_ui
    ports:
      - "8080:8080"
    networks:
      reverse-proxy:
        aliases:
          - event_ui
    environment:
      KAFKA_CLUSTERS_0_NAME: event_store
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: event_bus:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      SERVER_SERVLET_CONTEXT_PATH: /
    depends_on:
      - kafka

  product_service:
    build: .docker/node
    container_name: Kalat.Modules.Product
    command: bash -c "yarn install --immutable && yarn run start:dev"
    ports:
      - "3001:3000"
    working_dir: /usr/src/Kalat.Modules.Product
    volumes:
      - ./services/Kalat.Modules.Product:/usr/src/Kalat.Modules.Product
    environment:
      PORT: 3000
      DATABASE_URL: "mongodb://product_db:27017/product_db"
      KAFKA_BROKER: 'event_bus:9092'
      KAFKA_CONSUMER_GROUP: 'product-group'
      QUERY_TIMEOUT: 30000
      KAFKA_CONSUMER_RETRIES: 10
      KAFKA_CONSUMER_INITIAL_RETRY_TIME: 200
    networks:
      reverse-proxy:
        aliases:
          - event_product_service
    depends_on:
      - kafka
      - product_db

  product_db:
    image: mongo:latest
    container_name: event_product_db
    ports:
      - "27017:27017"
    volumes:
      - product_db:/data/db
    networks:
      reverse-proxy:
        aliases:
          - event_product_db
