---
# CNI (Container Network Interface) setup tasks

- name: Download Calico manifest
  ansible.builtin.get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: /tmp/calico.yaml
    mode: '0644'

- name: Create CNI directory
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'
    recurse: yes

- name: Load bridge module
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter module is loaded at boot
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/br_netfilter.conf
    line: br_netfilter
    create: yes
    mode: '0644'

- name: Set bridge-nf-call parameters
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s-bridge-nf.conf
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Ensure CNI configuration directory exists
  ansible.builtin.file:
    path: /etc/cni/net.d
    state: directory
    mode: '0755'
    recurse: yes
