apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: product
  name: mongo-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/mongo-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: product
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
