### GET request to example server
GET {{baseURL}}/products/6fbd720f-210d-4ee3-94c4-7f0bfd268bea

### POST Create product
POST {{baseURL}}/products
Content-Type: application/json

{
  "name": "{{$random.commerce.productName}}",
  "price": "{{$random.commerce.price}}"
}

