- name: Setup Kubernetes Control Plane
  hosts: localhost
  connection: local
  become: yes

  tasks:
    # Include system preparation tasks
    - name: System preparation
      include_tasks: tasks/system_prep.yaml

    # Include Kubernetes installation and configuration tasks
    - name: Kubernetes setup
      include_tasks: tasks/kubernetes_setup.yaml

    # Include Docker/containerd installation and configuration tasks
    - name: Containerd setup
      include_tasks: tasks/containerd_setup.yaml
