- name: Setup k8s master
  become: yes
  hosts: master
  tasks:
    # Include system preparation tasks
    - name: System preparation
      include_tasks: tasks/system_prep.yaml

    # Include Kubernetes installation and configuration tasks
    - name: Kubernetes setup
      include_tasks: tasks/kubernetes_setup.yaml

    # Include Docker/containerd installation and configuration tasks
    - name: Containerd setup
      include_tasks: tasks/containerd_setup.yaml

    # Include CNI setup tasks
    - name: CNI setup
      include_tasks: tasks/cni_setup.yaml

    # Include control plane initialization tasks
    - name: Control plane initialization
      include_tasks: tasks/control_plane_init.yaml
