@id = 12cce1ff-e1b1-43c8-9353-5a85c6a5539c

### GET a product by ID
GET {{baseURL}}/products/{{id}}

### GET all products
GET {{baseURL}}/products?page=0&limit=20

### POST product
POST {{baseURL}}/products
Content-Type: application/json

{
  "name": "{{$random.commerce.productName}}",
  "price": 22.20,
  "description": "{{$random.lorem.sentence}}",
  "currency": "USD",
  "image": "https://placehold.co/600x400"
}

### DELETE a product by ID
DELETE {{baseURL}}/products/{{id}}

### UPDATE a product
PATCH {{baseURL}}/products/{{id}}
Content-Type: application/json

{
  "name": "{{$random.commerce.productName}}",
  "price": 10.55,
  "description": "{{$random.lorem.sentence}}",
  "currency": "USD",
  "image": "https://placehold.co/600x400"
}
