### GET a product by ID
GET {{baseURL}}/products/{{id}}

### GET all products
GET {{baseURL}}/productsF

### POST product
POST {{baseURL}}/products
Content-Type: application/json

{
  "name": "{{$random.commerce.productName}}",
  "price": 22.20,
  "description": "{{$random.lorem.sentence}}",
  "currency": "USD"
}

> {%
  client.global.set('id', response.body.id)
%}

### archive a product by ID
DELETE {{baseURL}}/products/{{id}}

### enable a product by ID
PATCH {{baseURL}}/products/{{id}}/enable
Content-Type: application/json

{}

### disable a product by ID
PATCH {{baseURL}}/products/{{id}}/disable
Content-Type: application/json

{}

### UPDATE a product
PATCH {{baseURL}}/products/{{id}}
Content-Type: application/json

{
  "name": "{{$random.commerce.productName}}",
  "price": 10.55,
  "description": "{{$random.lorem.sentence}}",
  "currency": "USD",
  "image": "https://placehold.co/600x400"
}
